server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
    application:
        name: api-gateway
    cloud:
      gateway:
        discovery:
          locator:
            lower-case-service-id: true
            enabled: true
        routes:
          - id: user-service
            uri: lb://USER
            predicates:
              - Path=/api/v1/users/**

          - id: restaurant-service
            uri: lb://RESTAURANT
            predicates:
              - Path=/api/v1/restaurants/**

          - id: order-service
            uri: lb://ORDER
            predicates:
              - Path=/api/v1/cart/**
